AllCops:
  RunRailsCops: true

Metrics/LineLength:
  Max: 100

Style/DotPosition:
  EnforcedStyle: leading

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: single_quotes
